Avoid terms "Primary/Secondary Resource"
w3c/did-resolution pull request #96
Opened 2024-11-14 15:44 UTC by peacekeeper

This PR addresses https://github.com/w3c/did-resolution/issues/94 and replaces https://github.com/w3c/did-resolution/pull/89.

It now has section headings called "Dereferencing the Resource" and "Dereferencing the Fragment" instead of using "Primary Resource" and "Secondary Resource" (except in a small note that references RFC3986).

2024-11-14 16:26 UTC, msporny approved these changes

2024-11-14 16:27 UTC, msporny commented on index.html
> +				For example, if the resource is a representation of a DID document with media type <code>application/did+ld+json</code>, then
```suggestion
				For example, if the resource is a representation of a DID document with media type <code>application/did</code>, then
```

2024-11-14 18:45 UTC, TallTed requested changes
Small stuff. Editorial.

2024-11-14 18:45 UTC, TallTed commented on index.html
> +		resource, and dereferencing the fragment (only if the <var>input <a>DID URL</a></var> contains a <a>DID fragment</a>):</p>
```suggestion
		In accordance with [[RFC3986]], it consists of the following three steps: resolving the DID; dereferencing the
		resource; and dereferencing the fragment (only if the <var>input <a>DID URL</a></var> contains a <a>DID fragment</a>):</p>
```

2024-11-14 18:45 UTC, TallTed commented on index.html
> +					Otherwise, the result is called the <var>resolved <a>DID document</a></var>.</li>
just human-facing whitespace
```suggestion
						DID parameters</a> of the <var>input <a>DID URL</a></var> MUST be passed as <var>resolution options</var> to the
						<a>DID Resolution</a> algorithm. If the <var>input <a>DID</a></var> does not exist, return a null result.
						Otherwise, the result is called the <var>resolved <a>DID document</a></var>.</li>
```

2024-11-14 18:45 UTC, TallTed commented on index.html
> +					with the <var>input <a>DID URL</a></var> adjusted accordingly.</li>
```suggestion
					with the adjusted <var>input <a>DID URL</a></var>.</li>
```

2024-11-15 05:10 UTC, danpape approved these changes
Looks good.

2024-12-12 09:33 UTC, peacekeeper commented
Merging after several approvals, suggestions applied, and merge conflicts resolved.

2024-12-12 09:33 UTC, merged